name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  crd2pulumi:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: pulumi/crd2pulumi
          tag: v1.0.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  change-aws-credentials:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: jaxxstorm/change-aws-credentials
          tag: v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: change-aws-credentials version
  tf2pulumi:
    strategy:
      matrix:
        version: ["v0.7.0", "v0.8.0", "latest"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: pulumi/tf2pulumi
          tag: ${{ matrix.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: tf2pulumi version
  tfsec:
    strategy:
      matrix:
        version: ["v1.18.0", "v1.19.0", "latest"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
        arch: ["amd64"]
        include:
          - runs-on: "ubuntu-latest"
            platform: linux
          - runs-on: "macos-latest"
            platform: darwin
          - runs-on: "windows-latest"
            platform: windows
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: aquasecurity/tfsec
          tag: ${{ matrix.version }}
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: tfsec --version
